### PR TITLE
modifications for pymodaq v4 compatibiltiy

### PR DESCRIPTION
**Pull request by seb5g**
Added correct imports from v4 

Modified plugins following new template

simplifies access to parameters values

### CODE REVIEW

**Comment by seb5g** [comment]
Hi @quantumm could you test this with pymodaq v4 and your smaract MCS2? I'm testing it with other controllers MCS and SCU.

**Comment by seb5g** [comment]
Using this with SCU is ok!

**Comment by seb5g** [comment]
I talked recently with the guys of smaract about this. I told them it would be much better to release their library on pypi and I suggest you tell them this also. 

Is you plugin compatible only with MCS2? Is the python SDK able to handle old MCS and SCU controllers?

From what I saw in you plugin, the `smaract.ctl` wrapper is just a python replication of the C library. I think one need a proper python object where all the shitty things (like the error management) is included and hidden. But we'll see that when you create you pull request ;-)

And by the way, you can now easily access Parameter's value using: 
```
self.settings.child("stage_parameters", 'step_amplitude').value() 

self.settings["stage_parameters", 'step_amplitude']
```
it makes the code more concise...

**Comment by rgeneaux** [comment]
Hi,
This does not work for MCS2, and probably won't with MCS:
`+comon_parameters_fun(is_multiaxes, axes_names, epsilon=_epsilon)`

It looks like v4 requires that axes_names is a list of strings, not integers. 
But all library functions require to pass the axis index as integer! 

I guess the argument in all calls could be replaced by `int(self.settings['multiaxes','axis'])`. But this seems inefficient, since probably all motor controllers with multiaxes will have the same issue.

**Comment by seb5g** [comment]
Well originally I had only motor IDs with letters U, V. X, Y, Z.... So it was fine but if you really need integer then you're right it's ugly...

I think the solution lies with something I never tried. The list type Parameter can take as limits a dict. I think the printed values are then the keys strings but the parameter value can then either be a string or anything else. I'll look into this soon and make sure it will not collide with other pymodaq feature.

**Comment by seb5g** [comment]
About this idea of using dicts for list, here is a short minimal working example:

```
import sys

from qtpy.QtWidgets import QApplication
import pyqtgraph as pg

from pyqtgraph.parametertree import Parameter, ParameterTree


limits = {'a':21, 't':'hjk', '1':1}

param =[ {'name': 'list', 'type': 'list', 'limits': limits}]


if __name__ == '__main__':
    app = QApplication(sys.argv)
    
    widget = ParameterTree()
    settings = Parameter.create(name='test', type='group', children= param)
    widget.setParameters(settings)
    
    def print_settings(param: Parameter):
        print(f'value:{param.value()}, type: {type(param.value())}')
    
    settings.child('list').sigValueChanged.connect(print_settings)
    
    widget.show()
    app.exec()
```

try it and let me know if this would solve our issue!

**Comment by rgeneaux** [comment]
Ok this almost works, thanks!!

1. In daq_move everything is great:

`axes_names= {'Axis 1': 0, 'Axis 2': 1, 'Axis 3': 2}

    params = [
                 {'title': 'group parameter:',
                  'name': 'group_parameter',
                  'type': 'group',
                  'children': [
                     {'title': 'Controller Name:',
                      'name': 'smaract_mcs2',
                      'type': 'str',
                      'value': 'SmarAct MCS2 controller',
                      'readonly': True},
                     {'title': 'Controller locator',
                      'name': 'controller_locator', 'type': 'list',
                      'limits': controller_locators},
                  ]}
                ] + comon_parameters_fun(is_multiaxes, axes_names, epsilon=_epsilon)`

works right off the bat:
image


2. However, when put into a dashboard preset, the axis property is not stored properly (it only keeps the string list):

`<axis type="list" title="Axis:" visible="1" removable="0" readonly="0" values="['Axis 1', 'Axis 2', 'Axis 3']" limits="['Axis 1', 'Axis 2', 'Axis 3']" show_pb="1">
str('Axis 3')</axis>`
So the dashboard loads axis 1 everytime, despite having "Axis 3" selected here. 


3. In a final implementation, it would be nice if the axes names ('Axis 3' here) could be changeable by the plugin and not hard coded. Upon initializaiton, some controllers have some way of reading the real axis names, that would be nice to display!

**Comment by seb5g** [comment]
Hi there,
the new pymodaq release 4.0.7 should solve all this. I created a Mock actuator for the occasion and tested similar behaviour. The limits are now being taken care of if they are list or dict! Also, I added in the base class some methods to deal with axis name/names: 
http://pymodaq.cnrs.fr/en/latest/api/api_control_modules/API_DAQMove_Module.html#pymodaq.control_modules.move_utility_classes.DAQ_Move_base.axis_name

using this within the plugin, one should be able to modify the displayed names. Test it please.

Finally I introduced in the plugin template (and pymodaq_plugins_mock) a way to create a configuration file and to modify it on the computer or on the user level (same as the main configuration file). I'll make a paragraph in the doc about this!

**Comment by rgeneaux** [comment]
Hi, thanks!

1. The plugin works with the axes_names as dict! if you accept my PR on the pymo_v4 branch I think it will update this PR, which you can accept then (I don't have pushing rights on this repo)

2. I wasn't able to use the axis_names setter. It does not update the displayed options of self.settings.child('multiaxes', 'axis'). i'll test some more. 

3. Regarding the config files, here when I click on the new icon "Show Plugin Config" (icon left of "Refresh Value") it opens the main config_pymodaq.toml, is this normal? And in the parameter tree, the "Show Config" button inside the Main Settings group does nothing

**Comment by seb5g** [comment]
1. The plugin works with the axes_names as dict! if you accept my PR on the pymo_v4 branch I think it will update this PR, which you can accept then (I don't have pushing rights on this repo)

ok

2. I wasn't able to use the axis_names setter. It does not update the displayed options of self.settings.child('multiaxes', 'axis'). i'll test some more. 

I published a new branch and PR [#PyMoDAQ ](https://github.com/PyMoDAQ/PyMoDAQ/pull/149) to make sure calling these methods update accordingly the UI. Was not working because using param.opts['limits'] doesn't trigger the update settings but using: param.setLimits() now does the job


3. Regarding the config files, here when I click on the new icon "Show Plugin Config" (icon left of "Refresh Value") it opens the main config_pymodaq.toml, is this normal? And in the parameter tree, the "Show Config" button inside the Main Settings group does nothing

for the icon this is normal but for clarity I will swap the icons between show_settings  and the show_config
As for the button inside the main group, it will open the plugin config if there is a defined config. If you look at the last version of the plugin template, you'll notice a new folder called resources:

image

In there you can add a template of the config toml file for your plugin. Please try it, then pressing the button will make a copy of the template in the .pymodaq folder. That will be the base config of the plugin package. 
For instance for the last version of the pymodaq_plugins_mock:
image

 then each user can modify its own user config (.pymodaq in the user home) to modify the config of the plugins accordingly to their own needs

**Pull request merged**
